import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import BgBeamDemo from "@/components/BgBeamDemo";

const IBM_Plex = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-IBM_Plex",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={IBM_Plex.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <BgBeamDemo>{children}</BgBeamDemo>
        </ThemeProvider>
      </body>
    </html>
  );
}
